### PR TITLE
Added: Optionally include secondary results in HDF5 output

### PR DESCRIPTION
**Pull request by kmokstad**
Also add the -dumpNodeMap option to align with LinEl app.

### CODE REVIEW

**Comment by kmokstad** [comment]
jenkins build this please

**Comment by kmokstad** [comment]
jenkins build this please

**Comment by akva2** [comment]
since you seem to be incorporating fixes into this PR
```c++
diff --git a/FFlLib/FFlFEParts/FFlPLOAD.H b/FFlLib/FFlFEParts/FFlPLOAD.H
index 9e62613..bd310a2 100644
--- a/FFlLib/FFlFEParts/FFlPLOAD.H
+++ b/FFlLib/FFlFEParts/FFlPLOAD.H
@@ -35,6 +35,7 @@ public:
   virtual int getLoad(std::vector<FaVec3>& p, int& face) const;
 
 protected:
+  using FFlLoadBase::getTarget;
   virtual const FFlElementBase* getTarget(int& face) const = 0;
 
 private:
diff --git a/FFlLib/FFlFEParts/FFlQUAD4.C b/FFlLib/FFlFEParts/FFlQUAD4.C
index 978230b..785b22f 100644
--- a/FFlLib/FFlFEParts/FFlQUAD4.C
+++ b/FFlLib/FFlFEParts/FFlQUAD4.C
@@ -132,7 +132,7 @@ bool FFlQUAD4::invertMapping(const FaVec3& X, double* Xi) const
   FaVec3 v2(this->getNode(2)->getPos());
   FaVec3 v3(this->getNode(3)->getPos());
   FaVec3 v4(this->getNode(4)->getPos());
-  FaMat33 T = T.makeGlobalizedCS(v1,v2,v3,v4).transpose();
+  auto T = FaMat33{}.makeGlobalizedCS(v1,v2,v3,v4).transpose();
   FaVec3 Xp = T*X;
   FaVec3 X1 = T*v1;
   FaVec3 X2 = T*v2;
```

**Comment by kmokstad** [comment]
Found a better solution to the last issue above, which I also hope is fine wrt. gcc 13?

jenkins build this please

**Pull request merged**
